/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BuildMyAppRouteImport } from './routes/build-my-app'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DigitalTeachingBoardRouteImport } from './routes/digital-teaching-board'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StoreRouteImport } from './routes/store'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildMyAppRoute = BuildMyAppRouteImport.update({
  id: '/build-my-app',
  path: '/build-my-app',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTeachingBoardRoute = DigitalTeachingBoardRouteImport.update({
  id: '/digital-teaching-board',
  path: '/digital-teaching-board',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/build-my-app': typeof BuildMyAppRoute
  '/contact': typeof ContactRoute
  '/digital-teaching-board': typeof DigitalTeachingBoardRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/store': typeof StoreRouteWithChildren
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/store/$slug': typeof StoreSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/build-my-app': typeof BuildMyAppRoute
  '/contact': typeof ContactRoute
  '/digital-teaching-board': typeof DigitalTeachingBoardRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/store': typeof StoreRouteWithChildren
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/store/$slug': typeof StoreSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/build-my-app': typeof BuildMyAppRoute
  '/contact': typeof ContactRoute
  '/digital-teaching-board': typeof DigitalTeachingBoardRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/store': typeof StoreRouteWithChildren
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/store/$slug': typeof StoreSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/blog'
    | '/build-my-app'
    | '/contact'
    | '/digital-teaching-board'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/process'
    | '/services'
    | '/store'
    | '/terms'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/store/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/blog'
    | '/build-my-app'
    | '/contact'
    | '/digital-teaching-board'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/process'
    | '/services'
    | '/store'
    | '/terms'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/store/$slug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/blog'
    | '/build-my-app'
    | '/contact'
    | '/digital-teaching-board'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/process'
    | '/services'
    | '/store'
    | '/terms'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/store/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  BuildMyAppRoute: typeof BuildMyAppRoute
  ContactRoute: typeof ContactRoute
  DigitalTeachingBoardRoute: typeof DigitalTeachingBoardRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRoute
  StoreRoute: typeof StoreRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-my-app': {
      id: '/build-my-app'
      path: '/build-my-app'
      fullPath: '/build-my-app'
      preLoaderRoute: typeof BuildMyAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-teaching-board': {
      id: '/digital-teaching-board'
      path: '/digital-teaching-board'
      fullPath: '/digital-teaching-board'
      preLoaderRoute: typeof DigitalTeachingBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof StoreRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface StoreRouteChildren {
  StoreSlugRoute: typeof StoreSlugRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreSlugRoute: StoreSlugRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  BuildMyAppRoute: BuildMyAppRoute,
  ContactRoute: ContactRoute,
  DigitalTeachingBoardRoute: DigitalTeachingBoardRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRoute,
  StoreRoute: StoreRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
